"use client";

import { AlertCircle, LoaderCircle, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Card } from "@/components/ui/primitives";

type Envelope<T> = { success: boolean; data?: T; error?: { message?: string } };
type ReportData = { generatedAt: string; currency: string; sales: { summary: { transactionCount: number; grossSales: string; paidSales: string; outstandingSales: string }; trend: Array<{ date: string; total: string; transactionCount: number }>; topItems: Array<{ itemId: string; itemName: string; sku: string | null; quantity: string; revenue: string }> }; stock: { lowStockCount: number; outOfStockCount: number; items: Array<{ itemId: string; itemName: string; sku: string | null; threshold: string | null; onHand: string; reserved: string; available: string; isLowStock: boolean }> }; finance: { receivables: string; payables: string; cash: string; bank: string } };
const money = (value: string, currency: string) => `${currency} ${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function ReportsPage() {
  const [data, setData] = useState<ReportData | null>(null); const [tab, setTab] = useState<"sales" | "stock" | "items">("sales"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); const params = new URLSearchParams(); if (dateFrom) params.set("dateFrom", dateFrom); if (dateTo) params.set("dateTo", dateTo); try { const response = await fetch(`/api/reports/dashboard?${params}`); const body = await response.json() as Envelope<ReportData>; if (!response.ok || !body.success || !body.data) throw new Error(body.error?.message || "Unable to load reports"); setData(body.data); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load reports"); } finally { setLoading(false); } }, [dateFrom, dateTo]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <main className="page-content reports-page"><div className="finance-loading"><LoaderCircle className="spin" size={22} />Loading reports</div></main>;
  if (error || !data) return <main className="page-content reports-page"><div className="inline-error" role="alert"><AlertCircle size={22} /><strong>Reports are unavailable</strong><p>{error || "No report data was returned."}</p><button className="button button-outline" onClick={() => void load()}><RefreshCw size={15} />Try again</button></div></main>;
  return <main className="page-content reports-page"><header className="finance-header"><div><p className="eyebrow">REPORTS</p><h1>Business reports</h1><p className="page-description">Server-side summaries from posted sales, current stock balances, and authoritative finance ledgers.</p></div><button className="button button-outline" onClick={() => void load()}><RefreshCw size={15} />Refresh</button></header><form className="report-filter-bar" onSubmit={(event) => { event.preventDefault(); void load(); }}><label>From<input type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} /></label><label>To<input type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} /></label><button className="button" type="submit">Apply filters</button></form><nav className="finance-tabs" aria-label="Report views">{([["sales", "Sales summary"], ["stock", "Stock status"], ["items", "Top items"]] as const).map(([value, label]) => <button className={tab === value ? "finance-tab-active" : ""} key={value} onClick={() => setTab(value)}>{label}</button>)}</nav>{tab === "sales" && <SalesReport data={data} />}{tab === "stock" && <StockReport data={data} />}{tab === "items" && <ItemsReport data={data} />}</main>;
}

function SalesReport({ data }: { data: ReportData }) { return <><div className="finance-metrics"><ReportMetric label="Posted sales" value={money(data.sales.summary.grossSales, data.currency)} /><ReportMetric label="Paid sales" value={money(data.sales.summary.paidSales, data.currency)} /><ReportMetric label="Outstanding sales" value={money(data.sales.summary.outstandingSales, data.currency)} /><ReportMetric label="Transactions" value={String(data.sales.summary.transactionCount)} /></div><ReportTable title="Sales by date" headers={["Date", "Transactions", "Total"]} rows={data.sales.trend.map((row) => [row.date, String(row.transactionCount), money(row.total, data.currency)])} empty="No posted sales match the selected dates." /></>; }
function StockReport({ data }: { data: ReportData }) { return <><div className="finance-metrics"><ReportMetric label="Low stock items" value={String(data.stock.lowStockCount)} /><ReportMetric label="Out of stock" value={String(data.stock.outOfStockCount)} /></div><ReportTable title="Current stock status" headers={["Item", "SKU", "On hand", "Reserved", "Available", "Threshold"]} rows={data.stock.items.map((row) => [row.itemName, row.sku || "-", row.onHand, row.reserved, row.available, row.threshold || "-"])} empty="No active items found." /></>; }
function ItemsReport({ data }: { data: ReportData }) { return <ReportTable title="Top-selling items" headers={["Item", "SKU", "Quantity", "Revenue"]} rows={data.sales.topItems.map((row) => [row.itemName, row.sku || "-", row.quantity, money(row.revenue, data.currency)])} empty="No posted item sales match the selected dates." />; }
function ReportMetric({ label, value }: { label: string; value: string }) { return <Card className="finance-metric"><span className="metric-label">{label}</span><strong className="finance-metric-value">{value}</strong></Card>; }
function ReportTable({ title, headers, rows, empty }: { title: string; headers: string[]; rows: string[][]; empty: string }) { return <Card className="finance-panel"><div className="card-heading"><div><h2>{title}</h2><p>Values are returned by a tenant-scoped server aggregate.</p></div><span className="table-count">{rows.length} rows</span></div>{rows.length === 0 ? <div className="inline-empty"><strong>No report data</strong><p>{empty}</p></div> : <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.map((value, cellIndex) => <td className={cellIndex > 1 ? "numeric" : undefined} key={`${value}-${cellIndex}`}>{value}</td>)}</tr>)}</tbody></table></div>}</Card>; }